# Generated by Django 2.0.5 on 2018-07-03 16:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'report_city',
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('district', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'report_district',
            },
        ),
        migrations.CreateModel(
            name='DistrictCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.City')),
                ('district', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.DO_NOTHING, to='report.District')),
            ],
            options={
                'db_table': 'report_district_city',
            },
        ),
        migrations.CreateModel(
            name='MalfunctionData',
            fields=[
                ('city', models.CharField(blank=True, db_column='city', max_length=6, null=True)),
                ('profession', models.CharField(blank=True, db_column='profession', max_length=20, null=True)),
                ('department', models.CharField(blank=True, db_column='department', max_length=200, null=True)),
                ('malfunctionCity', models.CharField(blank=True, db_column='malfunctionCity', max_length=6, null=True)),
                ('receiptNumber', models.CharField(db_column='receiptNumber', max_length=20, primary_key=True, serialize=False)),
                ('receiptSerialNumber', models.CharField(db_column='receiptSerialNumber', max_length=20)),
                ('receiptStatus', models.CharField(blank=True, db_column='receiptStatus', max_length=10, null=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('distributeTime', models.DateTimeField(db_column='distributeTime')),
                ('processTime', models.IntegerField(blank=True, db_column='processTime', null=True)),
                ('hangTime', models.IntegerField(db_column='hangTime')),
                ('malfunctionSource', models.CharField(blank=True, db_column='malfunctionSource', max_length=50, null=True)),
                ('isTimeOut', models.CharField(blank=True, db_column='isTimeOut', max_length=2, null=True)),
                ('dutyDepartment', models.CharField(blank=True, db_column='dutyDepartment', max_length=200, null=True)),
                ('conclusion', models.CharField(blank=True, max_length=1024, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('reasonClassification', models.CharField(blank=True, db_column='reasonClassification', max_length=50, null=True)),
                ('malfunctionJudgment', models.CharField(blank=True, db_column='malfunctionJudgment', max_length=50, null=True)),
                ('malfunctionReason', models.CharField(blank=True, db_column='malfunctionReason', max_length=50, null=True)),
                ('originProfession', models.CharField(blank=True, db_column='originProfession', max_length=20, null=True)),
            ],
            options={
                'db_table': 'report_malfunction_data',
            },
        ),
        migrations.CreateModel(
            name='StatisticsAmount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearNum', models.SmallIntegerField(blank=True, null=True)),
                ('quarterNum', models.IntegerField(blank=True, null=True)),
                ('monthNum', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('profession', models.CharField(blank=True, max_length=10, null=True)),
                ('statisticsType', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_statistics_amount',
            },
        ),
        migrations.CreateModel(
            name='StatisticsDealTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearNum', models.SmallIntegerField(blank=True, db_column='yearNum', null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('monthNum', models.IntegerField(blank=True, db_column='monthNum', null=True)),
                ('quarterNum', models.IntegerField(blank=True, db_column='quarterNum', null=True)),
                ('statisticsType', models.IntegerField(blank=True, db_column='statisticsType', null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_statistics_deal_time',
            },
        ),
        migrations.CreateModel(
            name='StatisticsInTimeRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearNum', models.SmallIntegerField(blank=True, null=True)),
                ('city', models.TextField(blank=True, null=True)),
                ('monthNum', models.IntegerField(blank=True, null=True)),
                ('quarterNum', models.IntegerField(blank=True, null=True)),
                ('statisticsType', models.IntegerField(blank=True, null=True)),
                ('result', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_statistics_in_time_rate',
            },
        ),
        migrations.CreateModel(
            name='StatisticsOver48Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearNum', models.SmallIntegerField(blank=True, db_column='yearNum', null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('monthNum', models.IntegerField(blank=True, db_column='monthNum', null=True)),
                ('quarterNum', models.IntegerField(blank=True, db_column='quarterNum', null=True)),
                ('statisticsType', models.IntegerField(blank=True, db_column='statisticsType', null=True)),
                ('result', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_statistics_over48_rate',
            },
        ),
        migrations.CreateModel(
            name='StatisticsSpecificDealTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearNum', models.SmallIntegerField(blank=True, db_column='yearNum', null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('monthNum', models.IntegerField(blank=True, db_column='monthNum', null=True)),
                ('quarterNum', models.IntegerField(blank=True, db_column='quarterNum', null=True)),
                ('statisticsType', models.IntegerField(blank=True, db_column='statisticsType', null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
                ('reason', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'report_statistics_specific_deal_time',
            },
        ),
    ]
