# Generated by Django 2.0.5 on 2018-09-11 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatisticsReason',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('yearNum', models.SmallIntegerField(blank=True, db_column='yearNum', null=True)),
                ('monthNum', models.IntegerField(blank=True, db_column='monthNum', null=True)),
                ('quarterNum', models.IntegerField(blank=True, db_column='quarterNum', null=True)),
                ('dayNum', models.IntegerField(blank=True, null=True)),
                ('statisticsType', models.IntegerField(blank=True, db_column='statisticsType', null=True)),
                ('reason', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_statistics_reason',
            },
        ),
        migrations.CreateModel(
            name='StatisticsReceive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('yearNum', models.SmallIntegerField(blank=True, db_column='yearNum', null=True)),
                ('monthNum', models.IntegerField(blank=True, db_column='monthNum', null=True)),
                ('quarterNum', models.IntegerField(blank=True, db_column='quarterNum', null=True)),
                ('dayNum', models.IntegerField(blank=True, null=True)),
                ('statisticsType', models.IntegerField(blank=True, db_column='statisticsType', null=True)),
                ('result', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_statistics_receive',
            },
        ),
        migrations.AddField(
            model_name='statisticsamount',
            name='dayNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticsdealtime',
            name='dayNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticsintimerate',
            name='dayNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticsover48rate',
            name='dayNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='statisticsspecificdealtime',
            name='dayNum',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='malfunctiondata',
            name='city',
            field=models.CharField(blank=True, db_column='city', db_index=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='malfunctiondata',
            name='distributeTime',
            field=models.DateTimeField(db_column='distributeTime', db_index=True),
        ),
        migrations.AlterField(
            model_name='malfunctiondata',
            name='isTimeOut',
            field=models.CharField(blank=True, db_column='isTimeOut', db_index=True, max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='malfunctiondata',
            name='malfunctionJudgment',
            field=models.CharField(blank=True, db_column='malfunctionJudgment', db_index=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='malfunctiondata',
            name='processTime',
            field=models.IntegerField(blank=True, db_column='processTime', db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='malfunctiondata',
            name='profession',
            field=models.CharField(blank=True, db_column='profession', db_index=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='statisticsdealtime',
            name='result',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='statisticsspecificdealtime',
            name='result',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
