# Generated by Django 2.0.5 on 2018-06-17 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MalfunctionData',
            fields=[
                ('city', models.CharField(blank=True, db_column='City', max_length=6, null=True)),
                ('profession', models.CharField(blank=True, db_column='Profession', max_length=20, null=True)),
                ('department', models.CharField(blank=True, db_column='Department', max_length=200, null=True)),
                ('malfunctionCity', models.CharField(blank=True, db_column='malfunctionCity', max_length=6, null=True)),
                ('receiptNumber', models.CharField(db_column='receiptNumber', max_length=20, primary_key=True, serialize=False)),
                ('receiptSerialNumber', models.CharField(db_column='receiptSerialNumber', max_length=20)),
                ('receiptStatus', models.CharField(blank=True, db_column='receiptStatus', max_length=10, null=True)),
                ('title', models.CharField(max_length=200)),
                ('category', models.CharField(blank=True, max_length=200, null=True)),
                ('distributeTime', models.DateTimeField(db_column='distributeTime')),
                ('processTime', models.IntegerField(blank=True, db_column='processTime', null=True)),
                ('hangTime', models.IntegerField(db_column='hangTime')),
                ('malfunctionSource', models.CharField(blank=True, db_column='malfunctionSource', max_length=50, null=True)),
                ('isTimeOut', models.CharField(blank=True, db_column='isTimeOut', max_length=2, null=True)),
                ('dutyDepartment', models.CharField(blank=True, db_column='dutyDepartment', max_length=200, null=True)),
                ('conclusion', models.CharField(blank=True, max_length=1024, null=True)),
                ('type', models.CharField(blank=True, max_length=20, null=True)),
                ('reasonClassification', models.CharField(blank=True, db_column='reasonClassification', max_length=50, null=True)),
                ('malfunctionJudgment', models.CharField(blank=True, db_column='malfunctionJudgment', max_length=50, null=True)),
                ('malfunctionReason', models.CharField(blank=True, db_column='malfunctionReason', max_length=50, null=True)),
                ('originProfession', models.CharField(blank=True, db_column='originProfession', max_length=20, null=True)),
            ],
            options={
                'db_table': 'malfunction_data',
                'managed': False,
            },
        ),
    ]
