# Generated by Django 2.0.5 on 2018-09-11 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20180911_2140'),
    ]

    operations = [
        migrations.AddField(
            model_name='malfunctiondata',
            name='ne',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
