# Generated by Django 2.0.5 on 2018-06-19 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_malfunctiondata'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'report_city',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('district', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'db_table': 'report_district',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DistrictCity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'report_district_city',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='malfunctiondata',
            table='report_malfunction_data',
        ),
    ]
