# Generated by Django 2.0.5 on 2018-06-28 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20180619_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportStatistics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yearNum', models.SmallIntegerField(blank=True, null=True)),
                ('quarterNum', models.IntegerField(blank=True, null=True)),
                ('monthNum', models.IntegerField(blank=True, null=True)),
                ('city', models.CharField(blank=True, max_length=10, null=True)),
                ('statisticsType', models.CharField(blank=True, max_length=20, null=True)),
                ('result', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'report_statistics',
                'managed': False,
            },
        ),
    ]
