INSERT INTO .report_city (id, city) VALUES (1, '广州');
INSERT INTO .report_city (id, city) VALUES (2, '深圳');
INSERT INTO .report_city (id, city) VALUES (3, '东莞');
INSERT INTO .report_city (id, city) VALUES (4, '佛山');
INSERT INTO .report_city (id, city) VALUES (5, '中山');
INSERT INTO .report_city (id, city) VALUES (6, '惠州');
INSERT INTO .report_city (id, city) VALUES (7, '江门');
INSERT INTO .report_city (id, city) VALUES (8, '珠海');
INSERT INTO .report_city (id, city) VALUES (9, '汕头');
INSERT INTO .report_city (id, city) VALUES (10, '汕尾');
INSERT INTO .report_city (id, city) VALUES (11, '揭阳');
INSERT INTO .report_city (id, city) VALUES (12, '潮州');
INSERT INTO .report_city (id, city) VALUES (13, '云浮');
INSERT INTO .report_city (id, city) VALUES (14, '阳江');
INSERT INTO .report_city (id, city) VALUES (15, '湛江');
INSERT INTO .report_city (id, city) VALUES (16, '茂名');
INSERT INTO .report_city (id, city) VALUES (17, '河源');
INSERT INTO .report_city (id, city) VALUES (18, '清远');
INSERT INTO .report_city (id, city) VALUES (19, '肇庆');
INSERT INTO .report_city (id, city) VALUES (20, '梅州');
INSERT INTO .report_city (id, city) VALUES (21, '韶关');

INSERT INTO .report_district (id, district) VALUES (1, '珠1');
INSERT INTO .report_district (id, district) VALUES (2, '珠2');
INSERT INTO .report_district (id, district) VALUES (3, '粤东');
INSERT INTO .report_district (id, district) VALUES (4, '粤西');
INSERT INTO .report_district (id, district) VALUES (5, '粤北');

INSERT INTO .report_district_city (id, city_id, district_id) VALUES (1, 1, 1);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (2, 2, 1);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (3, 3, 1);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (4, 4, 1);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (5, 5, 2);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (6, 6, 2);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (7, 7, 2);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (8, 8, 2);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (9, 9, 3);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (10, 10, 3);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (11, 11, 3);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (12, 12, 3);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (13, 13, 4);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (14, 14, 4);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (15, 15, 4);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (16, 16, 4);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (17, 17, 5);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (18, 18, 5);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (19, 19, 5);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (20, 20, 5);
INSERT INTO .report_district_city (id, city_id, district_id) VALUES (21, 21, 5);

